version: '3'

services:
  nginx1:
    build:
      context: ./nginx1
      dockerfile: Dockerfile
    networks:
      - nginx-network

  nginx2:
    build:
      context: ./nginx2
      dockerfile: Dockerfile
    networks:
      - nginx-network

  nginx-proxy:
    image: nginx
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge

