# Use the official Nginx image as the base
FROM nginx:latest

# Copy the content from the local directory to the container
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80
